### ISSUE TITLE
Prework Final Project Prep Part I: Setting Up Your Repo

### ISSUE THREAD

**Issue by evareitzel** [learn-co-curriculum/phase-0-project-prep-part-1#2]
### Canvas Link

https://learning.flatironschool.com/courses/5290/pages/prework-final-project-prep-part-i-setting-up-your-repo?module_item_id=356981

### Concern

Possible update: Change ""Branch 'main' set up to track remote branch 'main' from 'origin'." to "branch 'main' set up to track 'origin/main'."

### Suggested Changes

see above.

**Comment by professor-ben** [comment]
Hi Eva,

I've been unable to reproduce this message in my own console. I'm seeing the original quote when I do. This might have something to do with your syntax or the way you've set up Git from your command line. Either way, it looks like what you're doing is working- 'main' from 'origin' means the same as 'origin/main' in Git speak.

Thanks,
Ben
